test:
  COGNITO_POOL_ARN: YOUR_POOL_ARN
  COGNITO_POOL_ID: COGNITO_POOL_ID
  COGNITO_CLIENT_ID: COGNITO_CLIENT_ID

stage:
  COGNITO_POOL_ARN: COGNITO_POOL_ARN
  COGNITO_POOL_ID: COGNITO_POOL_ID
  COGNITO_CLIENT_ID: COGNITO_CLIENT_ID
prod:
  COGNITO_POOL_ARN: COGNITO_POOL_ARN
  COGNITO_POOL_ID: COGNITO_POOL_ID
  COGNITO_CLIENT_ID: COGNITO_CLIENT_ID